apiVersion: v2
name: sonarr
description: Smart PVR for newsgroup and bittorrent users
type: application
version: 1.1.2
# renovate: image=ghcr.io/onedr0p/sonarr
appVersion: "3.0.10.1567"
keywords:
  - sonarr
  - servarr
  - torrent
  - usenet
home: https://github.com/pree/helm-charts/tree/master/charts/sonarr
icon: https://raw.githubusercontent.com/Sonarr/Sonarr/develop/Logo/512.png
sources:
  - https://github.com/Sonarr/Sonarr
  - https://github.com/onedr0p/containers
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.3.2
