apiVersion: v2
name: readarr
description: Book Manager and Automation (Sonarr for Ebooks)
type: application
version: 1.4.0
# renovate: image=ghcr.io/onedr0p/readarr-develop
appVersion: "0.3.14.2348"
keywords:
  - readarr
  - servarr
  - torrent
  - usenet
home: https://github.com/pree/helm-charts/tree/master/charts/readarr
icon: https://raw.githubusercontent.com/Readarr/Readarr/develop/Logo/512.png
sources:
  - https://github.com/Readarr/Readarr
  - https://github.com/onedr0p/containers
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.5.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: use template to generate README.md
