apiVersion: v2
name: media-apps
description: Argo CD app-of-apps config for media applications
type: application
# version and appVersion are in sync in this chart!
version: 0.3.14
appVersion: 0.3.14
home: https://git.reeb.io/pree/helm-charts/src/branch/master/charts/media-apps
sources:
  - https://git.reeb.io/pree/helm-charts
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: argoconfig
    version: 0.9.0
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: changed prowlarr to https://charts.pree.dev
