apiVersion: v2
name: media-apps
description: Argo CD app-of-apps config for media applications
type: application
# version and appVersion are in sync in this chart!
version: 0.6.27
appVersion: 0.6.27
home: https://github.com/pree/helm-charts/tree/master/charts/media-apps
sources:
  - https://github.com/pree/helm-charts
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: argoconfig
    version: 0.9.1
    repository: https://charts.adfinis.com
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: use template to generate README.md
