apiVersion: v2
name: radarr
description: A fork of Sonarr to work with movies Ã  la Couchpotato
type: application
version: 1.16.0
# renovate: image=ghcr.io/home-operations/radarr
appVersion: "5.22.3.9889"
keywords:
  - radarr
  - servarr
  - torrent
  - usenet
home: https://github.com/pree/helm-charts/tree/master/charts/radarr
icon: https://raw.githubusercontent.com/Radarr/Radarr/develop/Logo/512.png
sources:
  - https://github.com/Radarr/Radarr
  - https://github.com/home-operations/containers
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.5.1
annotations:
  artifacthub.io/changes: |
    - kind: changed
      description: use template to generate README.md
