apiVersion: v2
name: prowlarr
description: Prowlarr is an indexer manager/proxy built on the popular *arr .net/reactjs base stack to integrate with your various PVR apps
type: application
version: 1.8.1
# renovate: image=ghcr.io/onedr0p/prowlarr-develop
appVersion: "1.4.1.3258"
keywords:
  - prowlarr
  - servarr
  - torrent
  - usenet
home: https://github.com/pree/helm-charts/tree/master/charts/radarr
icon: https://raw.githubusercontent.com/Prowlarr/Prowlarr/develop/Logo/512.png
sources:
  - https://github.com/Prowlarr/Prowlarr
  - https://github.com/onedr0p/containers
maintainers:
  - name: pree
    email: pascal@reeb.io
dependencies:
  - name: common
    repository: https://bjw-s.github.io/helm-charts/
    version: 1.5.1
